# 1. Cargar los datos.

In [2]:
import pandas as pd
datos = pd.read_csv("/content/sample_data/datosprocesados2.csv")

In [3]:
datos.head()

,Id,MSZoning,LotFrontage,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,X3SsnPorch,ScreenPorch,MiscVal,MoSold,Reforma,outlier
0,1,RL,65.0,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,...,548,0,61,0,0,0,0,2,5,False
1,2,RL,80.0,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,...,460,298,0,0,0,0,0,5,31,False
2,3,RL,68.0,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,...,608,0,42,0,0,0,0,9,6,False
3,4,RL,60.0,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,...,642,0,35,272,0,0,0,2,36,True
4,5,RL,84.0,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,...,836,192,84,0,0,0,0,12,8,True

In [4]:
# prompt: datos de columnas de valores perdidos

import pandas as pd

# Suponiendo que 'datos' es tu DataFrame
# Reemplaza 'datos' con el nombre real de tu DataFrame

# Para obtener los datos de las columnas con valores perdidos:
missing_data = datos.isnull().sum()

# Imprime los datos de las columnas con valores perdidos:
missing_data

Id                0
MSZoning          0
LotFrontage     259
Street            0
Alley          1369
               ...
ScreenPorch       0
MiscVal           0
MoSold            0
Reforma           0
outlier           0
Length: 84, dtype: int64

# 2. Comprobar el número de valores perdidos. (En total y variable por variable)

# 3. Realizar la misma operación en porcentajes

# 4. Realizar diagramas de los valores perdidos que permitan ver su número y posición

# 5. Realizar un gráfico de correlación de los valores perdidos.

# 6. Eliminar aquellas variables que tengan más de un 30% de valores perdidos

# 7. Calcular el porcentaje de valores perdidos una vez eliminadas esas variables.

# 8. Eliminar de las tres primeras variables los NAs (sin incluir la Id).

# 9. Eliminar de todas las variables los valores perdidos.

# 10. Comprobar que no existen valores perdidos.

# 11. Volver a cargar los datos.

# 12. Imputar la media a los valores perdidos.

# 13. Comprobar que no existen valores perdidos.

En caso de que no se haya eliminado explicar a qué puede deberse.

# 14. Volver a cargar los datos.

# 15. Imputar los valores perdidos utilizando la imputación múltiple.

# 16. Guardar los datos.